services:
  pdi:
    build:
      context: .
      dockerfile: Dockerfile
    
    # Tells Compose which file to pull the values from
    env_file:
      - .env
    
    # The name of the image it will create
    image: pdi:0.5.4
